### ISSUE TITLE
setParagraphStyle not working

### ISSUE THREAD

**Issue by ghysrc** [youngsoft/MyAttributedString#1]
NSMutableParagraphStyle *mps = [[NSMutableParagraphStyle alloc]init];
[mps setAlignment:NSTextAlignmentCenter];
[[builder allRange] setParagraphStyle:mps];
label.attributedText = builer.commit;

设置完之后，文本还是靠左边对齐的。

**Comment by youngsoft** [comment]
我把DEMO上改了一下是可以的。 builder = [[MyAttributedStringBuilder alloc] initWithString:@"两只老虎，两只老虎 跑得快，跑得快"];
            NSMutableParagraphStyle *mps = [[NSMutableParagraphStyle alloc]init];
            [mps setAlignment:NSTextAlignmentCenter];
            [[builder allRange] setParagraphStyle:mps];

```
    }
        break;
    default:
        break;
}

cell.textLabel.attributedText = builder.commit;
```

居中显示。我估计是你是否label的宽度设置的不够宽。。。

**Comment by ghysrc** [comment]
Sorry，我的错，没仔细检查代码就来了。发现我在设置居中后面还有一句
[[builder allRange] setLineSpacing:5];
把前面的效果覆盖了，写到ParagraphStyle里就好了
[mps setLineSpacing:5];

谢了，你的这个类真是简单易用。
